---
- name: DESIGNING A CUSTOM MODULE
  hello_world:
  register: result
  tags: test_01


- name: PRINTING RETURN
  ansible.builtin.debug: var=result
  tags: test_01


- name: FILTER USERS OUT OF COUCHDB
  ansible.builtin.uri:
    url: http://couchdb:5984/mydb/_find
    user: admin
    password: password
    method: POST
    body:
      selector:
        doc_type: users
    force_basic_auth: true
    body_format: json
  register: couchdb_results
  tags: test_03


- name: UPDATE FACT USERS FROM COUCHDB
  ansible.builtin.set_fact:
    users: "{{ couchdb_results.json.docs }}"
  tags: test_03


- name: CALL ME
  call_me:
    name: "{{ item.name }}"
    telephone: "{{ item.telephone }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ users }}"
  loop_control:
    label: "{{ item.doc.name | default('undefined') }}"
  register: result
  tags: test_02, test_03


- name: PRINTING RETURN
  ansible.builtin.debug: var=result
  tags: test_02, test_03